from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
INIT = SCRIPTS / "init_training_package.py"
VALIDATE = SCRIPTS / "validate_human_package.py"
REVIEW = SCRIPTS / "review_human_package.py"


HEADINGS = (
    "## 1 题目要求", "## 2 直接答案", "## 3 与其他问题的关系",
    "## 4 数据与输入", "## 5 假设", "## 6 变量与符号",
    "## 7 模型选择及理由", "## 8 模型建立与公式", "## 9 求解过程",
    "## 10 最终结果", "## 11 图表与论文位置", "## 12 验证",
    "## 13 局限", "## 14 写作禁区",
)


def filled_solution(include_rejected: bool = True) -> str:
    parts = []
    for heading in HEADINGS:
        content = "本节给出可追溯且明确的最终内容。"
        if heading == "## 14 写作禁区" and include_rejected:
            content += " 禁止采用 process/q1/routes/r02-old/route.md 中的废弃口径。"
        parts.append(f"{heading}\n\n{content}")
    return "# Q1 final solution\n\n" + "\n\n".join(parts) + "\n"


class HumanPackageTests(unittest.TestCase):
    def run_script(self, script: Path, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(script), *args], check=False,
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )

    def scaffold(self, root: Path) -> Path:
        package = root / "training-99-human"
        result = self.run_script(
            INIT, str(package), "--package-id", "training-99-human",
            "--title", "Case one", "--questions", "q1",
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        return package

    def finalize(self, package: Path, *, include_rejected_in_ban: bool = True) -> None:
        process_files = {
            "process/q1/routes/r01-baseline/route.md": "adopted model and derivation\n",
            "process/q1/routes/r01-baseline/notes/full-reasoning.md": (
                "# Full reasoning\n\nInput enters the adopted model, parameters are "
                "determined, the algorithm runs, and the result is interpreted.\n"
            ),
            "process/q1/routes/r01-baseline/code/main.py": "print('ok')\n",
            "process/q1/routes/r01-baseline/runs/run-20260808-1430-default/run.md": "command and inputs\n",
            "process/q1/routes/r01-baseline/runs/run-20260808-1430-default/results/result.json": '{"answer": 1}\n',
            "process/q1/routes/r01-baseline/runs/run-20260808-1430-default/validation/check.json": '{"ok": true}\n',
            "process/q1/routes/r02-old/route.md": "rejected old model\n",
        }
        for relative, content in process_files.items():
            path = package / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

        final_files = {
            "final/README.md": "# Canonical final\n\nGenerated by the Finalizer Skill.\n",
            "final/common/assumptions.md": "# Assumptions\n\nAssumptions are fixed.\n",
            "final/common/notation.md": "# Notation\n\nNotation is fixed.\n",
            "final/common/dependency-map.md": "# Dependencies\n\nQ1 is independent.\n",
            "final/common/decision-log.md": (
                "# Decision log\n\n"
                "Adopted `process/q1/routes/r01-baseline/route.md`. "
                "Rejected `process/q1/routes/r02-old/route.md` because its input convention is obsolete.\n"
            ),
            "final/q1/solution.md": filled_solution(include_rejected_in_ban),
            "final/q1/full-reasoning.md": process_files[
                "process/q1/routes/r01-baseline/notes/full-reasoning.md"
            ],
            "final/q1/code/main.py": "print('ok')\n",
            "final/q1/results/result.json": '{"answer": 1}\n',
            "final/q1/validation/check.json": '{"ok": true}\n',
        }
        for relative, content in final_files.items():
            path = package / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

        common = [
            "final/README.md", "final/common/assumptions.md", "final/common/notation.md",
            "final/common/dependency-map.md", "final/common/decision-log.md",
        ]
        question_artifacts = [
            "final/q1/solution.md", "final/q1/full-reasoning.md", "final/q1/code/main.py",
            "final/q1/results/result.json", "final/q1/validation/check.json",
        ]
        manifest = {
            "schema_version": 3,
            "package_id": "training-99-human",
            "title": "Case one",
            "finalization_status": "ready_for_review",
            "generated_from_process": True,
            "writer_entrypoint": "final",
            "process_policy": "noncanonical",
            "source_files": [],
            "external_input_note": "Official inputs are supplied outside this fixture.",
            "common_files": common,
            "common_provenance": [
                {"final_artifact": value, "process_sources": ["process/q1/routes/r01-baseline/route.md"]}
                for value in common
            ],
            "unresolved_decisions": [],
            "questions": [{
                "id": "q1",
                "solution": "final/q1/solution.md",
                "source_inputs": ["external:official problem and attachment"],
                "final_code": ["final/q1/code/main.py"],
                "no_code_reason": "",
                "final_results": [
                    "final/q1/full-reasoning.md",
                    "final/q1/results/result.json",
                ],
                "no_machine_results_reason": "",
                "final_figures": [],
                "validation": {
                    "status": "verified",
                    "artifacts": ["final/q1/validation/check.json"],
                    "gap_reason": "",
                    "affected_conclusion": "Question one answer",
                },
                "route_decisions": {
                    "adopted": [{"artifact": "process/q1/routes/r01-baseline/route.md", "reason": "matches model and result"}],
                    "supporting": [],
                    "rejected": [{"artifact": "process/q1/routes/r02-old/route.md", "reason": "obsolete input convention"}],
                    "superseded": [],
                    "unresolved": [],
                },
                "provenance": [
                    {"final_artifact": value, "process_sources": [
                        "process/q1/routes/r01-baseline/code/main.py" if "/code/" in value else
                        "process/q1/routes/r01-baseline/notes/full-reasoning.md" if value.endswith("/full-reasoning.md") else
                        "process/q1/routes/r01-baseline/runs/run-20260808-1430-default/validation/check.json" if "/validation/" in value else
                        "process/q1/routes/r01-baseline/runs/run-20260808-1430-default/results/result.json" if "/results/" in value else
                        "process/q1/routes/r01-baseline/route.md"
                    ]}
                    for value in question_artifacts
                ],
            }],
        }
        (package / "human-package.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

    def test_adopted_reasoning_can_be_copied_without_rewriting(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            process_reasoning = package / "process/q1/routes/r01-baseline/notes/full-reasoning.md"
            final_reasoning = package / "final/q1/full-reasoning.md"
            result = self.run_script(VALIDATE, str(package))
            self.assertEqual(process_reasoning.read_bytes(), final_reasoning.read_bytes())
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_intake_contains_no_final_or_generated_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            result = self.run_script(VALIDATE, str(package))
            self.assertFalse((package / "final").exists())
            self.assertFalse((package / "human-package.json").exists())
            self.assertFalse((package / "approval.json").exists())
        self.assertEqual(result.returncode, 2)
        self.assertIn("INTAKE", result.stdout)

    def test_intake_uses_route_centered_process_layers(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            required = (
                "source/problem", "source/attachments", "source/external",
                "process/_staging",
                "process/common/notes", "process/common/data", "process/common/code",
                "process/common/results", "process/common/figures",
                "process/q1/inbox", "process/q1/routes",
                "process/q1/comparisons", "process/q1/decisions",
            )
            for relative in required:
                self.assertTrue((package / relative).is_dir(), relative)
            question_index = (package / "process/q1/README.md").read_text(encoding="utf-8")
            staging_index = (package / "process/_staging/README.md").read_text(encoding="utf-8")
            staging_log_exists = (package / "process/_staging/classification-log.md").is_file()
            guide = (package / "PROCESS_GUIDE.md").read_text(encoding="utf-8")
        self.assertIn("routes/rNN-short-name", question_index)
        self.assertIn("classification-log.md", staging_index)
        self.assertTrue(staging_log_exists)
        self.assertIn("目录放什么", guide)
        self.assertIn("### route.md", guide)
        self.assertIn("### run.md", guide)
        self.assertIn("移交前最低检查", guide)

    def test_clean_intake_reaches_finalizer_receiving_gate(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 2)
        self.assertIn("INTAKE", result.stdout)

    def test_unclassified_staging_file_blocks_finalization(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            loose = package / "process/_staging/loose-chat-export.md"
            loose.write_text("unclassified route notes\n", encoding="utf-8")
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)
        self.assertIn("unclassified file remains in process/_staging/", result.stdout)
        self.assertIn("not ready for finalization", result.stdout)

    def test_missing_staging_control_file_blocks_finalization(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            (package / "process/_staging/classification-log.md").unlink()
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)
        self.assertIn("missing required staging control file", result.stdout)

    def test_generated_final_is_valid_but_pending_cannot_be_written(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            valid = self.run_script(VALIDATE, str(package))
            pending = self.run_script(REVIEW, str(package), "--pending")
            writing = self.run_script(VALIDATE, str(package), "--require-approved")
        self.assertEqual(valid.returncode, 0, valid.stdout + valid.stderr)
        self.assertEqual(pending.returncode, 0, pending.stdout + pending.stderr)
        self.assertEqual(writing.returncode, 1)
        self.assertIn("not approved", writing.stdout)

    def test_human_approval_hashes_enable_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            approved = self.run_script(REVIEW, str(package), "--approve", "--reviewer", "human")
            writing = self.run_script(VALIDATE, str(package), "--require-approved")
        self.assertEqual(approved.returncode, 0, approved.stdout + approved.stderr)
        self.assertEqual(writing.returncode, 0, writing.stdout + writing.stderr)
        self.assertIn("approval=current", writing.stdout)

    def test_edit_after_approval_invalidates_hash(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            self.assertEqual(self.run_script(REVIEW, str(package), "--approve", "--reviewer", "human").returncode, 0)
            solution = package / "final/q1/solution.md"
            solution.write_text(solution.read_text(encoding="utf-8") + "\n审核后改动。\n", encoding="utf-8")
            writing = self.run_script(VALIDATE, str(package), "--require-approved")
        self.assertEqual(writing.returncode, 1)
        self.assertIn("final/ tree changed after review", writing.stdout)

    def test_unresolved_conflict_cannot_be_approved(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            alternative = package / "process/q1/routes/r03-alternative/route.md"
            alternative.parent.mkdir(parents=True)
            alternative.write_text("incompatible objective\n", encoding="utf-8")
            manifest_path = package / "human-package.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["finalization_status"] = "needs_decision"
            manifest["unresolved_decisions"] = ["Choose the original or alternative objective"]
            manifest["questions"][0]["route_decisions"]["unresolved"] = [
                {"artifact": "process/q1/routes/r03-alternative/route.md", "reason": "objectives conflict"}
            ]
            manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            log = package / "final/common/decision-log.md"
            log.write_text(log.read_text(encoding="utf-8") + "Unresolved `process/q1/routes/r03-alternative/route.md`.\n", encoding="utf-8")
            approved = self.run_script(REVIEW, str(package), "--approve", "--reviewer", "human")
        self.assertEqual(approved.returncode, 1)
        self.assertIn("unresolved decisions block approval", approved.stdout)

    def test_rejected_route_must_be_in_writing_ban(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package, include_rejected_in_ban=False)
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)
        self.assertIn("missing from solution writing-ban section", result.stdout)

    def test_route_directory_requires_standard_name_and_route_record(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            (package / "process/q1/routes/latest version").mkdir()
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)
        self.assertIn("invalid route directory name", result.stdout)
        self.assertIn("route.md", result.stdout)

    def test_process_file_cannot_be_a_final_artifact(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            manifest_path = package / "human-package.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["questions"][0]["final_results"] = ["process/q1/routes/r01-baseline/runs/run-20260808-1430-default/results/result.json"]
            manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)

    def test_unreferenced_final_file_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            package = self.scaffold(Path(temporary))
            self.finalize(package)
            (package / "final/q1/results/latest-copy.csv").write_text("x\n1\n", encoding="utf-8")
            result = self.run_script(VALIDATE, str(package))
        self.assertEqual(result.returncode, 1)
        self.assertIn("unreferenced file in final/", result.stdout)

    def test_package_without_intake_or_manifest_is_legacy(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            legacy = Path(temporary) / "legacy"
            legacy.mkdir()
            (legacy / "notes.txt").write_text("old package\n", encoding="utf-8")
            result = self.run_script(VALIDATE, str(legacy))
        self.assertEqual(result.returncode, 2)
        self.assertIn("LEGACY", result.stdout)


if __name__ == "__main__":
    unittest.main()
